// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp_CoreWebAPI.Models;

namespace QuizApp_CoreWebAPI.Migrations.McqDB
{
    [DbContext(typeof(McqDBContext))]
    [Migration("20210312125906_six")]
    partial class six
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizApp_CoreWebAPI.Models.McqQuestion", b =>
                {
                    b.Property<int>("McqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mcqId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ans")
                        .HasColumnName("ans")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ExtraAnswer")
                        .HasColumnName("extraAnswer")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Img")
                        .HasColumnName("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnName("question")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("QuestionNo")
                        .HasColumnName("questionNo")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("QuizType")
                        .HasColumnName("quizType")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("McqId")
                        .HasName("PK__mcqQuest__FD2C2EC251467301");

                    b.ToTable("mcqQuestion");
                });
#pragma warning restore 612, 618
        }
    }
}
